apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Values.global.environment }}
spec:
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP