apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "database.fullname" . }}-externalsecret
  namespace: database
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: {{ .Values.aws.clusterSecretStoreName }}
    kind: ClusterSecretStore

  target:
    name: {{ include "database.fullname" . }}-credentials
    creationPolicy: Owner

  data:
    - secretKey: MYSQL_USER
      remoteRef:
        key: {{ .Values.aws.secretName }}
        property: username

    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: {{ .Values.aws.secretName }}
        property: password

    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.aws.secretName }}
        property: rootPassword