apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-allow-backend-only
  namespace: {{ .Values.global.environment }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: database
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: backend
      ports:
        - protocol: TCP
          port: 3306
    - from:
        - podSelector:
            matchLabels:
              job-name: {{ printf "%s-database-migration" .Release.Name }}
      ports:
        - protocol: TCP
          port: 3306