image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

service:
  port: 3306

storage:
  storageClassName: efs-sc
  size: 5Gi

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

mysql:
  database: "appdb"

aws:
  region: "eu-west-1"
  serviceAccountName: "external-secrets"
  secretName: "poc2/mysql-credentials"
  clusterSecretStoreName: "aws-secrets-store"