frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: 231733667519.dkr.ecr.eu-west-1.amazonaws.com/poc2-three-tier-frontend
    tag: "v1"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

backend:
  enabled: true
  replicaCount: 1
  image:
    repository: 231733667519.dkr.ecr.eu-west-1.amazonaws.com/poc2-three-tier-backend
    tag: "v1"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

database:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  storage:
    storageClassName: efs-sc
    size: 5Gi
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

aws:
  region: "eu-west-1"
  serviceAccountName: "external-secrets"
  clusterSecretStoreName: "aws-secrets-store"