apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.aws.clusterSecretStoreName }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.serviceAccountName }}
            namespace: external-secrets