apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: backend
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          env:
            - name: DB_HOST
              value: {{ printf "%s-database.database.svc.cluster.local" .Release.Name | quote }}
            - name: DB_PORT
              value: {{ .Values.db.port | quote }}
            - name: DB_DATABASE
              value: {{ .Values.db.name | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-db-credentials
                  key: MYSQL_USER
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-db-credentials
                  key: MYSQL_PASSWORD

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 20